{% set version = "1.4.1" %}

package:
    name: wordcloud
    version: {{ version }}

source:
    url: https://github.com/amueller/word_cloud/archive/{{ version }}.tar.gz
    fn: wordcloud-{{ version }}.tar.gz
    sha256: bb1da374261919600b29746af6668fd90722ac15a564226bde42a236bba07588

build:
    number: 1000
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip


    run:
        - python
        - pillow
        - numpy

test:
    imports:
        - wordcloud
    commands:
        - wordcloud_cli.py -h

about:
    home: https://github.com/amueller/word_cloud
    license: MIT
    summary: A little word cloud generator in Python

extra:
    recipe-maintainers:
        - amueller
        - ericdill
