{% set version = "1.8.2.2" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://github.com/amueller/word_cloud/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9c80c8ad279b7402e780d1ec03c5e2ee83a0192e61e76c23cc7f9306cc5b5012

build:
  number: 2
  script:
    - cythonize --force wordcloud\query_integral_image.pyx  # [py>310 and win]
    - "${BUILD_PREFIX}/bin/python -m Cython.Build.Cythonize --force wordcloud/query_integral_image.pyx"  # [py>310 and not win]
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
  run:
    - python
    - pillow
    - numpy >=1.6.1
    - matplotlib-base

test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli -h

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
