{% set version = "1.9.4" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/w/wordcloud/wordcloud-{{ version }}.tar.gz
  sha256: b273d8a5ded97d3ead904046b49464dcb71119ee79df875072a4c105cadd347a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - setuptools-scm
    - toml
    - pip
    - cython >=0.29.33
  run:
    - python
    - numpy >=1.6.1
    - pillow
    - matplotlib-base

test:
  imports:
    - wordcloud
  commands:
    - pip check
    # make sure the version reported by pip is correct
    - "pip show {{ name }} | grep -Fx 'Version: {{ version }}'"
    - wordcloud_cli -h
  requires:
    - pip

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
