{% set version = "1.5.0" %}

package:
    name: wordcloud
    version: {{ version }}

source:
    url: https://github.com/amueller/word_cloud/archive/{{ version }}.tar.gz
    fn: wordcloud-{{ version }}.tar.gz
    sha256: 118ef31e51ea602d5f0246fd940757e8480d40194f8fb88bfd07e94fcb8babc8

build:
    number: 0
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip


    run:
        - python
        - pillow
        - numpy

test:
    imports:
        - wordcloud
    commands:
        - wordcloud_cli.py -h

about:
    home: https://github.com/amueller/word_cloud
    license: MIT
    summary: A little word cloud generator in Python

extra:
    recipe-maintainers:
        - amueller
        - ericdill
