{% set version = "1.3.3" %}

package:
    name: wordcloud
    version: {{ version }}

source:
    url: https://github.com/amueller/word_cloud/archive/{{ version }}.tar.gz
    fn: wordcloud-{{ version }}.tar.gz
    sha256: c96539261c1745d1f4141b88bc6a0bf29d82d8eb1dc490c4685fbcf71b5c6210

build:
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - pip


    run:
        - python
        - pillow
        - numpy

test:
    imports:
        - wordcloud
    commands:
        - wordcloud_cli.py -h

about:
    home: https://github.com/amueller/word_cloud
    license: MIT
    summary: A little word cloud generator in Python

extra:
    recipe-maintainers:
        - amueller
        - ericdill
