{% set version = "1.8.2.2" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wordcloud/wordcloud-{{ version }}.tar.gz
  sha256: 523db887e47e840eb5c2e60428243bb1d7439fdc60f89626b17bafa1be64459c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - pillow
    - numpy >=1.6.1
    - matplotlib-base

test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli -h

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
