{% set version = "1.9.3" %}

package:
  name: wordcloud
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/wordcloud/wordcloud-{{ version }}.tar.gz
  sha256: a9aa738d63ed674a40f0cc31adb83f4ca5fc195f03a6aff6e010d1f5807d1c58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - wordcloud_cli = wordcloud.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.33
  run:
    - python
    - numpy >=1.6.1
    - pillow
    - matplotlib-base

test:
  imports:
    - wordcloud
  commands:
    - pip check
    - wordcloud_cli -h
  requires:
    - pip

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  license_file: LICENSE
  summary: A little word cloud generator in Python

extra:
  recipe-maintainers:
    - amueller
    - ericdill
    - ocefpaf
